## 주어진 데이터에서 상위 10개 국가의 접종률 평균과 하위 10개 국가의 접종률 평균을 구하고, 그 차이를 구해보세요 
### (단, 100%가 넘는 접종률 제거, 소수 첫째자리까지 출력)

- 데이터셋 : ../input/covid-vaccination-vs-death/covid-vaccination-vs-death_ratio.csv
- 오른쪽 상단 copy&edit 클릭 -> 예상문제 풀이 시작

In [52]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
import numpy as np

df = pd.read_csv('../input/covid-vaccination-vs-death/covid-vaccination-vs-death_ratio.csv')
df.head()

,Unnamed: 0,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,New_deaths,population,ratio
0,0,Afghanistan,AFG,2021-05-11,504502.0,448878.0,55624.0,12,40374668.0,1.111781
1,1,Afghanistan,AFG,2021-05-20,547901.0,470341.0,77560.0,10,40374668.0,1.164941
2,2,Afghanistan,AFG,2021-05-24,573277.0,476367.0,96910.0,10,40374668.0,1.179866
3,3,Afghanistan,AFG,2021-05-26,590454.0,479372.0,111082.0,19,40374668.0,1.187309
4,4,Afghanistan,AFG,2021-05-27,593313.0,479574.0,113739.0,14,40374668.0,1.187809

In [54]:
# 국가별 접종률 

df2 = df.groupby('country').max()
df2.head()

,Unnamed: 0,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,New_deaths,population,ratio
country,,,,,,,,,
Afghanistan,35,AFG,2022-03-22,5751015.0,5082824.0,4420127.0,86,40374668.0,12.589141
Albania,219,ALB,2022-03-24,2754244.0,1278902.0,1215199.0,18,2869700.0,44.565704
Algeria,239,DZA,2022-03-09,13704895.0,7461932.0,6110712.0,34,45061896.0,16.559294
Andorra,270,AND,2022-03-13,151997.0,57817.0,53367.0,2,77355.0,74.742421
Angola,323,AGO,2022-03-25,17535411.0,11235059.0,5993792.0,18,34566172.0,32.503047

In [55]:
# 내림차순으로 정렬하기

df2 = df2.sort_values(by = 'ratio', ascending = False)
df2['ratio'].head()

country
Gibraltar               124.737373
Malta                   106.760570
Niue                    101.914762
United Arab Emirates     98.397065
Portugal                 95.204947
Name: ratio, dtype: float64

In [56]:
# 100% 넘는 접종률 제거

df2 = df2.drop(index = df2[df2['ratio']>100].index)
df2['ratio'].head()

country
United Arab Emirates    98.397065
Portugal                95.204947
Cuba                    93.972331
Chile                   92.654748
Brunei Darussalam       91.899582
Name: ratio, dtype: float64

In [57]:
# 상위 10개 국가와 하위 10개 국가의 평균값 구하고, 차이 구하기(소수 첫째점자리까지)
top = df2['ratio'].head(10).mean()
print(top)

bottom = df2['ratio'].tail(10).mean()
print(bottom)

print(round(top - bottom,1))

91.81697544672713
3.4504083912453525
88.4